---
Name: iqmailchimp
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - IQnection\Mailchimp\SiteConfig\SiteConfig
---
Only:
  classexists: 
    - IQnection\FormPage\FormPage
    - IQnection\FormPage\Model\FormPageSubmission
---
IQnection\FormPage\FormPage:
  extensions:
    - IQnection\Mailchimp\FormPage\FormPage
IQnection\FormPage\Model\FormPageSubmission:
  extensions:
    - IQnection\Mailchimp\FormPage\Model\FormPageSubmission
---